
version: "3.3"

services:

  db:
    image: postgres:14.2-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminerr
    ports:
      - 8080:8080

networks:
  internal:

volumes:
  data:
  
